#!/bin/bash

if [ -z $1 ]; then echo "You must provide folder path"; exit; fi

RED='\033[0;31m'
NC='\033[0m' # No Color

newfile="replayTrace.csv"

#OLDIFS=$IFS
#IFS=" "
IdT=1
IdC=1
IdSG=1

current="vide" #Pour passer le premier coup
#fait un cut sur le début et passer les lignes.
while read ligne
do
    #Tant que ligne contient current continue
     current="$(cut -d \" \" )"
     #traitement
     #if current contient _T_
     ##Alors tracer
     ##sinon si current contient _C_
     ###alors codes
     ###sinon inconnu
     ##fin si
     #fin si
done < find -R $1 -name "*"

#IFS=$OLDIFS

rm $newfile
rm dragonfly*
rm -r tracer-out*
rm ross.csv
